SUMMARY = "cproto - generate C function prototypes and convert function definitions"
HOMEPAGE = "https://invisible-island.net/cproto/"

# public domain, except the autoconf scripting, which is MIT-X11
LICENSE = "PD & MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=4175b2965868e5f090026b0ef85b29ea"

SRC_URI = "https://invisible-mirror.net/archives/cproto/cproto-${PV}.tgz"
SRC_URI[sha256sum] = "0cccb93447682c7fdb4f0bdbfbe05d52a827331e0a19a5215d2c3cb85ad29258"

S = "${UNPACKDIR}/${BPN}-${PV}"

DEPENDS = "flex-native bison-native"

inherit autotools native

# cproto ships a working configure (generated by Dickey's patched autoconf
# 2.52) that supports out-of-tree builds and DESTDIR. Regenerating it with a
# modern autoconf does not work, so skip autoreconf and run it as shipped.
# This is what the old "Fix autotools build to work with Yocto" patch -- a
# wholesale replacement of the build system -- used to work around.
do_configure() {
    oe_runconf
}
